travis:
  secure:
    BINSTAR_TOKEN: RZ74Oo349V5utgtJqZRNVuHnUtAjCKGYwWCZ4OD+9zTHpx/24AFIbJSj4FBwGFTKi3Q6qguoQkGzP83gWEH7YjeCtPxyYauK5OQc8Dh7e2rQUfiQCfPfJo/lyeOFk6V0v7Di7R4Xecm5EjJiPSCEY7UxGGvVzI64ecHRcTZFPWmfpoXt49Po7mDu5FcXYSc/ToVLJYlLT+/zl42X7G0bU8E6IWNT9F/KYuvKB7T5I8O3howkJIr/qOSEi+1eUtPJWJijj1iMjQ8JGQSpZhyI6sYvDp+vlRJrALZYZ6MfyGEVFmvC4Deq7lw2FOeOb9soyZZ6eMwx79yZofLcjiWcSQDPqyx0WrMoR6SJV6iQFjE2F/2yfRpzWiRLkwvn63NG+QT+LWyNk6MUKlVvV/qU12xB6IxQqU+lFWZUN+nmrb8mb3sXlfyn8ptuJ6LYAUZq1A8LLnlk3eTGljvLza7g8zIk0TylNAqwxC8k9X2ZIWYudzsmrjh6ZUUubpS8oboNglPzbhma+UpPgr2lGBF92cUO7wvtNOVWlk12s1K4KUVsF3DMR/TzLFnVUOwmzi/z7fV8b1RJxxRGkKaElqaxR6XbbGLHBWEzRqiHP/RUe1a1o/AwiObE0vtaDEaBRDf91N7/YjxhjABMJJJEGta2X6dOWCOIEWX3H9m9tiaBqms=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
